#! /bin/sh
# @(#) $Tau: kdc/docker/kdc/heimdal-kdc $

## ------------------------------------------------------------------------- ##
##                          T A U    P R O J E C T                           ##
## ------------------------------------------------------------------------- ##
##                                                                           ##
##  Licensed under the Apache License, Version 2.0 (the "License");          ##
##  you may not use this file except in compliance with the License.         ##
##                                                                           ##
##  You may obtain a copy of the License at:                                 ##
##                                                                           ##
##      http://www.apache.org/licenses/LICENSE-2.0                           ##
##                                                                           ##
##  Unless required by applicable law or agreed to in writing, software      ##
##  distributed under the License is distributed on an "AS-IS" BASIS,        ##
##  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. ##
##  See the License for the specific language governing permissions and      ##
##  limitations under the License.                                           ##
##                                                                           ##
## ------------------------------------------------------------------------- ##

KDC_ENABLED=${KDC_ENABLED:-yes}
KDC_PARAMS="${KDC_PARAMS:---config-file=/var/lib/heimdal-kdc/kdc.conf}"

KPASSWDD_ENABLED=${KPASSWDD_ENABLED:-yes}

MASTER_ENABLED=${MASTER_ENABLED:-yes}

SLAVE_ENABLED=${SLAVE_ENABLED:-no}

